--- #YAML:1.0
name: Alien-wxWidgets
version: 0.05
author:
  - Mattia Barbon <mbarbon@cpan.org>
abstract: building, finding and using wxWidgets binaries
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
